version: '3.8'

services:
  king-18:
    image: david-18
    build: .
    ports:
      - '7002:3000'
    environment:
      - MONGODB_URI:'mongodb://mongo:27017/store'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
